---

- name: "FreeBSD wpa-cli Debug"
  vars:
    msg: |
         ansible_architecture [ {{ ansible_architecture }} ]
         ansible_os_family [ {{ ansible_os_family }} ]
         ansible_distribution [ {{ ansible_distribution }} ]
         ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
         ansible_distribution_version [ {{ ansible_distribution_version }} ]
         ansible_distribution_release [ {{ ansible_distribution_release }} ]

         wpa_cli_enable [ {{ wpa_cli_enable }} ]
         wpacli_packages
         {{ wpacli_packages | to_nice_yaml }}
         wpacli_program [ {{ wpacli_program }} ]

         wpacli_pid_dir [ {{ wpacli_pid_dir }} ]
         wpacli_pid_dir_owner [ {{ wpacli_pid_dir_owner }} ]
         wpacli_pid_dir_group [ {{ wpacli_pid_dir_group }} ]
         wpacli_pid_dir_mode [ {{ wpacli_pid_dir_mode }} ]

         wpacli_action_script [ {{ wpacli_action_script }} ]
         wpacli_action_script_template [ {{ wpacli_action_script_template }} ]
         wpacli_action_script_dir [ {{ wpacli_action_script_dir }} ]
         wpacli_action_script_file [ {{ wpacli_action_script_file }} ]
         wpacli_action_script_owner [ {{ wpacli_action_script_owner }} ]
         wpacli_action_script_group [ {{ wpacli_action_script_group }} ]
         wpacli_action_script_mode [ {{ wpacli_action_script_mode }} ]
         wpacli_action_script_log_to_file [ {{ wpacli_action_script_log_to_file }} ]
         wpacli_action_script_logfile [ {{ wpacli_action_script_logfile }} ]

         wpacli_rcconf
         {{ wpacli_rcconf | to_yaml }}

         fp_wpasupplicant_conf_ctrl_interface [ {{ fp_wpasupplicant_conf_ctrl_interface|default('absent') }} ]
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
