---
# tasks for vbotka.freebsd_wpa_cli

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: wpacli_debug|bool
  tags: wpacli_debug

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags: [wpacli_assert, always]

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: wpacli_install|bool
  tags: wpacli_packages

- name: Import wpa-cli.yml
  ansible.builtin.import_tasks: wpa-cli.yml
  tags: wpacli_wpa_cli

- name: Import rc.yml
  ansible.builtin.import_tasks: rc.yml
  tags: wpacli_rc

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: wpacli_rc_conf

# EOF
