---
- name: "Packages: Install packages"
  community.general.pkgng:
    name: "{{ wpacli_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == 'packages'

- name: "Packages: Install ports"
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages | d(false) }}"
  loop: "{{ wpacli_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == 'ports'

# EOF
