---

- name: "rc: Create wpa_cli rc script /etc/rc.d/wpa_cli"
  template:
    src: wpa_cli.j2
    dest: "/etc/rc.d/wpa_cli"
    owner: "root"
    group: "wheel"
    mode: "0555"
    backup: "{{ wpacli_backup_conf }}"
  tags: wpacli_rc_script

- name: "rc: Patch /etc/defaults/rc.conf; add wpa_cli_* default vars"
  patch:
    src: "{{ role_path }}/files/rc.conf.patch"
    basedir: /etc/defaults
  tags: wpacli_rc_defaults_patch
 
- name: "rc: Patch /etc/network.subr, start/stop wpa_cli"
  patch:
    src: "{{ role_path }}/files/network.subr.patch"
    basedir: /etc
  tags: wpacli_rc_networksubr_patch
  
# EOF
...
