---

- name: "rcconf: Configure wpa_cli_* in /etc/rc.conf"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.val }}"'
    backup: "{{ wpacli_backup_conf }}"
  loop: "{{ wpacli_rcconf }}"
  notify: restart netif

# EOF
...
