---
- name: "Wpa-cli: Create pid dir {{ wpacli_pid_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ wpacli_pid_dir }}"
    owner: "{{ wpacli_pid_dir_owner }}"
    group: "{{ wpacli_pid_dir_group }}"
    mode: "{{ wpacli_pid_dir_mode }}"
  tags: wpacli_pid_dir

- name: "Wpa-cli: Create {{ wpacli_action_script_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ wpacli_action_script_dir }}"
    owner: "{{ wpacli_action_script_dir_owner }}"
    group: "{{ wpacli_action_script_dir_group }}"
    mode: "{{ wpacli_action_script_dir_mode }}"
  when: wpacli_action_script | bool
  tags: wpacli_action_script

- name: "Wpa-cli: Create action script {{ wpacli_action_script_dir ~ '/' ~ wpacli_action_script_file }}"
  ansible.builtin.template:
    src: "{{ wpacli_action_script_template }}"
    dest: "{{ wpacli_action_script_dir }}/{{ wpacli_action_script_file }}"
    owner: "{{ wpacli_action_script_owner }}"
    group: "{{ wpacli_action_script_group }}"
    mode: "{{ wpacli_action_script_mode }}"
    backup: "{{ wpacli_backup_conf }}"
  when: wpacli_action_script | bool
  tags: wpacli_action_script

# EOF
