---
# handlers file for vbotka.freebsd_wpa_cli

- name: Restart netif
  listen: restart netif
  ansible.builtin.service:
    name: netif
    state: restarted
  when: wpacli_enable | upper == 'YES'

# EOF
