---
- name: Create source/annotation-[tasks,handlers,templates].rst
  hosts: localhost
  gather_facts: false
  debugger: on_failed

  tasks:

    - tags: tasks
      block:
        - name: Include variables
          ansible.builtin.include_vars:
            file: annotation/annotation-tasks.yml
        - name: Create rst file
          ansible.builtin.template:
            src: annotation/annotation-tasks.rst.j2
            dest: source/annotation-tasks.rst

    - tags: handlers
      block:
        - name: Include variables
          ansible.builtin.include_vars:
            file: annotation/annotation-handlers.yml
        - name: Create rst file
          ansible.builtin.template:
            src: annotation/annotation-handlers.rst.j2
            dest: source/annotation-handlers.rst

    - tags: templates
      block:
        - name: Include variables
          ansible.builtin.include_vars:
            file: annotation/annotation-templates.yml
        - name: Create rst file
          ansible.builtin.template:
            src: annotation/annotation-templates.rst.j2
            dest: source/annotation-templates.rst

# EOF
